---
abstract: unknown
author:
  - unknown
  - 'Gtk2-Perl Team <gtk-perl-list at gnome dot org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  Data::Dumper: '0'
  ExtUtils::MakeMaker: '7.44'
  File::Spec: '0'
  IO::File: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.44, CPAN::Meta::Converter version 2.150010'
keywords:
  - XS
  - 'XS extensions'
  - dependency
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: ExtUtils-Depends
no_index:
  directory:
    - t
    - inc
  package:
    - ExtUtils::MM
requires:
  Data::Dumper: '0'
  ExtUtils::MakeMaker: '7.44'
  File::Spec: '0'
  IO::File: '0'
  perl: '5.006'
resources:
  MailingList: https://mail.gnome.org/mailman/listinfo/gtk-perl-list
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=ExtUtils-Depends
  homepage: http://gtk2-perl.sourceforge.net
  license: http://dev.perl.org/licenses/
  repository: git://git.gnome.org/perl-ExtUtils-Depends
version: '0.8001'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
